// Complete list of world countries with dial codes, flags, and nationalities
export interface Country {
  code: string; // Dial code like +880
  country: string; // Country name
  flag: string; // Emoji flag
  nationality: string; // Nationality name (e.g., "Bangladeshi")
  iso: string; // ISO 3166-1 alpha-2 code (e.g., "BD")
}

export const worldCountries: Country[] = [
  { code: "+93", country: "Afghanistan", flag: "🇦🇫", nationality: "Afghan", iso: "AF" },
  { code: "+355", country: "Albania", flag: "🇦🇱", nationality: "Albanian", iso: "AL" },
  { code: "+213", country: "Algeria", flag: "🇩🇿", nationality: "Algerian", iso: "DZ" },
  { code: "+376", country: "Andorra", flag: "🇦🇩", nationality: "Andorran", iso: "AD" },
  { code: "+244", country: "Angola", flag: "🇦🇴", nationality: "Angolan", iso: "AO" },
  { code: "+1268", country: "Antigua and Barbuda", flag: "🇦🇬", nationality: "Antiguan", iso: "AG" },
  { code: "+54", country: "Argentina", flag: "🇦🇷", nationality: "Argentine", iso: "AR" },
  { code: "+374", country: "Armenia", flag: "🇦🇲", nationality: "Armenian", iso: "AM" },
  { code: "+61", country: "Australia", flag: "🇦🇺", nationality: "Australian", iso: "AU" },
  { code: "+43", country: "Austria", flag: "🇦🇹", nationality: "Austrian", iso: "AT" },
  { code: "+994", country: "Azerbaijan", flag: "🇦🇿", nationality: "Azerbaijani", iso: "AZ" },
  { code: "+1242", country: "Bahamas", flag: "🇧🇸", nationality: "Bahamian", iso: "BS" },
  { code: "+973", country: "Bahrain", flag: "🇧🇭", nationality: "Bahraini", iso: "BH" },
  { code: "+880", country: "Bangladesh", flag: "🇧🇩", nationality: "Bangladeshi", iso: "BD" },
  { code: "+1246", country: "Barbados", flag: "🇧🇧", nationality: "Barbadian", iso: "BB" },
  { code: "+375", country: "Belarus", flag: "🇧🇾", nationality: "Belarusian", iso: "BY" },
  { code: "+32", country: "Belgium", flag: "🇧🇪", nationality: "Belgian", iso: "BE" },
  { code: "+501", country: "Belize", flag: "🇧🇿", nationality: "Belizean", iso: "BZ" },
  { code: "+229", country: "Benin", flag: "🇧🇯", nationality: "Beninese", iso: "BJ" },
  { code: "+975", country: "Bhutan", flag: "🇧🇹", nationality: "Bhutanese", iso: "BT" },
  { code: "+591", country: "Bolivia", flag: "🇧🇴", nationality: "Bolivian", iso: "BO" },
  { code: "+387", country: "Bosnia and Herzegovina", flag: "🇧🇦", nationality: "Bosnian", iso: "BA" },
  { code: "+267", country: "Botswana", flag: "🇧🇼", nationality: "Motswana", iso: "BW" },
  { code: "+55", country: "Brazil", flag: "🇧🇷", nationality: "Brazilian", iso: "BR" },
  { code: "+673", country: "Brunei", flag: "🇧🇳", nationality: "Bruneian", iso: "BN" },
  { code: "+359", country: "Bulgaria", flag: "🇧🇬", nationality: "Bulgarian", iso: "BG" },
  { code: "+226", country: "Burkina Faso", flag: "🇧🇫", nationality: "Burkinabe", iso: "BF" },
  { code: "+257", country: "Burundi", flag: "🇧🇮", nationality: "Burundian", iso: "BI" },
  { code: "+238", country: "Cabo Verde", flag: "🇨🇻", nationality: "Cape Verdean", iso: "CV" },
  { code: "+855", country: "Cambodia", flag: "🇰🇭", nationality: "Cambodian", iso: "KH" },
  { code: "+237", country: "Cameroon", flag: "🇨🇲", nationality: "Cameroonian", iso: "CM" },
  { code: "+1", country: "Canada", flag: "🇨🇦", nationality: "Canadian", iso: "CA" },
  { code: "+236", country: "Central African Republic", flag: "🇨🇫", nationality: "Central African", iso: "CF" },
  { code: "+235", country: "Chad", flag: "🇹🇩", nationality: "Chadian", iso: "TD" },
  { code: "+56", country: "Chile", flag: "🇨🇱", nationality: "Chilean", iso: "CL" },
  { code: "+86", country: "China", flag: "🇨🇳", nationality: "Chinese", iso: "CN" },
  { code: "+57", country: "Colombia", flag: "🇨🇴", nationality: "Colombian", iso: "CO" },
  { code: "+269", country: "Comoros", flag: "🇰🇲", nationality: "Comoran", iso: "KM" },
  { code: "+242", country: "Congo (Republic)", flag: "🇨🇬", nationality: "Congolese", iso: "CG" },
  { code: "+243", country: "Congo (DRC)", flag: "🇨🇩", nationality: "Congolese", iso: "CD" },
  { code: "+506", country: "Costa Rica", flag: "🇨🇷", nationality: "Costa Rican", iso: "CR" },
  { code: "+225", country: "Côte d'Ivoire", flag: "🇨🇮", nationality: "Ivorian", iso: "CI" },
  { code: "+385", country: "Croatia", flag: "🇭🇷", nationality: "Croatian", iso: "HR" },
  { code: "+53", country: "Cuba", flag: "🇨🇺", nationality: "Cuban", iso: "CU" },
  { code: "+357", country: "Cyprus", flag: "🇨🇾", nationality: "Cypriot", iso: "CY" },
  { code: "+420", country: "Czech Republic", flag: "🇨🇿", nationality: "Czech", iso: "CZ" },
  { code: "+45", country: "Denmark", flag: "🇩🇰", nationality: "Danish", iso: "DK" },
  { code: "+253", country: "Djibouti", flag: "🇩🇯", nationality: "Djiboutian", iso: "DJ" },
  { code: "+1767", country: "Dominica", flag: "🇩🇲", nationality: "Dominican", iso: "DM" },
  { code: "+1809", country: "Dominican Republic", flag: "🇩🇴", nationality: "Dominican", iso: "DO" },
  { code: "+670", country: "East Timor", flag: "🇹🇱", nationality: "East Timorese", iso: "TL" },
  { code: "+593", country: "Ecuador", flag: "🇪🇨", nationality: "Ecuadorian", iso: "EC" },
  { code: "+20", country: "Egypt", flag: "🇪🇬", nationality: "Egyptian", iso: "EG" },
  { code: "+503", country: "El Salvador", flag: "🇸🇻", nationality: "Salvadoran", iso: "SV" },
  { code: "+240", country: "Equatorial Guinea", flag: "🇬🇶", nationality: "Equatoguinean", iso: "GQ" },
  { code: "+291", country: "Eritrea", flag: "🇪🇷", nationality: "Eritrean", iso: "ER" },
  { code: "+372", country: "Estonia", flag: "🇪🇪", nationality: "Estonian", iso: "EE" },
  { code: "+268", country: "Eswatini", flag: "🇸🇿", nationality: "Swazi", iso: "SZ" },
  { code: "+251", country: "Ethiopia", flag: "🇪🇹", nationality: "Ethiopian", iso: "ET" },
  { code: "+679", country: "Fiji", flag: "🇫🇯", nationality: "Fijian", iso: "FJ" },
  { code: "+358", country: "Finland", flag: "🇫🇮", nationality: "Finnish", iso: "FI" },
  { code: "+33", country: "France", flag: "🇫🇷", nationality: "French", iso: "FR" },
  { code: "+241", country: "Gabon", flag: "🇬🇦", nationality: "Gabonese", iso: "GA" },
  { code: "+220", country: "Gambia", flag: "🇬🇲", nationality: "Gambian", iso: "GM" },
  { code: "+995", country: "Georgia", flag: "🇬🇪", nationality: "Georgian", iso: "GE" },
  { code: "+49", country: "Germany", flag: "🇩🇪", nationality: "German", iso: "DE" },
  { code: "+233", country: "Ghana", flag: "🇬🇭", nationality: "Ghanaian", iso: "GH" },
  { code: "+30", country: "Greece", flag: "🇬🇷", nationality: "Greek", iso: "GR" },
  { code: "+1473", country: "Grenada", flag: "🇬🇩", nationality: "Grenadian", iso: "GD" },
  { code: "+502", country: "Guatemala", flag: "🇬🇹", nationality: "Guatemalan", iso: "GT" },
  { code: "+224", country: "Guinea", flag: "🇬🇳", nationality: "Guinean", iso: "GN" },
  { code: "+245", country: "Guinea-Bissau", flag: "🇬🇼", nationality: "Bissau-Guinean", iso: "GW" },
  { code: "+592", country: "Guyana", flag: "🇬🇾", nationality: "Guyanese", iso: "GY" },
  { code: "+509", country: "Haiti", flag: "🇭🇹", nationality: "Haitian", iso: "HT" },
  { code: "+504", country: "Honduras", flag: "🇭🇳", nationality: "Honduran", iso: "HN" },
  { code: "+852", country: "Hong Kong", flag: "🇭🇰", nationality: "Hong Konger", iso: "HK" },
  { code: "+36", country: "Hungary", flag: "🇭🇺", nationality: "Hungarian", iso: "HU" },
  { code: "+354", country: "Iceland", flag: "🇮🇸", nationality: "Icelandic", iso: "IS" },
  { code: "+91", country: "India", flag: "🇮🇳", nationality: "Indian", iso: "IN" },
  { code: "+62", country: "Indonesia", flag: "🇮🇩", nationality: "Indonesian", iso: "ID" },
  { code: "+98", country: "Iran", flag: "🇮🇷", nationality: "Iranian", iso: "IR" },
  { code: "+964", country: "Iraq", flag: "🇮🇶", nationality: "Iraqi", iso: "IQ" },
  { code: "+353", country: "Ireland", flag: "🇮🇪", nationality: "Irish", iso: "IE" },
  { code: "+972", country: "Israel", flag: "🇮🇱", nationality: "Israeli", iso: "IL" },
  { code: "+39", country: "Italy", flag: "🇮🇹", nationality: "Italian", iso: "IT" },
  { code: "+1876", country: "Jamaica", flag: "🇯🇲", nationality: "Jamaican", iso: "JM" },
  { code: "+81", country: "Japan", flag: "🇯🇵", nationality: "Japanese", iso: "JP" },
  { code: "+962", country: "Jordan", flag: "🇯🇴", nationality: "Jordanian", iso: "JO" },
  { code: "+7", country: "Kazakhstan", flag: "🇰🇿", nationality: "Kazakhstani", iso: "KZ" },
  { code: "+254", country: "Kenya", flag: "🇰🇪", nationality: "Kenyan", iso: "KE" },
  { code: "+686", country: "Kiribati", flag: "🇰🇮", nationality: "I-Kiribati", iso: "KI" },
  { code: "+850", country: "North Korea", flag: "🇰🇵", nationality: "North Korean", iso: "KP" },
  { code: "+82", country: "South Korea", flag: "🇰🇷", nationality: "South Korean", iso: "KR" },
  { code: "+965", country: "Kuwait", flag: "🇰🇼", nationality: "Kuwaiti", iso: "KW" },
  { code: "+996", country: "Kyrgyzstan", flag: "🇰🇬", nationality: "Kyrgyz", iso: "KG" },
  { code: "+856", country: "Laos", flag: "🇱🇦", nationality: "Laotian", iso: "LA" },
  { code: "+371", country: "Latvia", flag: "🇱🇻", nationality: "Latvian", iso: "LV" },
  { code: "+961", country: "Lebanon", flag: "🇱🇧", nationality: "Lebanese", iso: "LB" },
  { code: "+266", country: "Lesotho", flag: "🇱🇸", nationality: "Mosotho", iso: "LS" },
  { code: "+231", country: "Liberia", flag: "🇱🇷", nationality: "Liberian", iso: "LR" },
  { code: "+218", country: "Libya", flag: "🇱🇾", nationality: "Libyan", iso: "LY" },
  { code: "+423", country: "Liechtenstein", flag: "🇱🇮", nationality: "Liechtensteiner", iso: "LI" },
  { code: "+370", country: "Lithuania", flag: "🇱🇹", nationality: "Lithuanian", iso: "LT" },
  { code: "+352", country: "Luxembourg", flag: "🇱🇺", nationality: "Luxembourger", iso: "LU" },
  { code: "+853", country: "Macau", flag: "🇲🇴", nationality: "Macanese", iso: "MO" },
  { code: "+261", country: "Madagascar", flag: "🇲🇬", nationality: "Malagasy", iso: "MG" },
  { code: "+265", country: "Malawi", flag: "🇲🇼", nationality: "Malawian", iso: "MW" },
  { code: "+60", country: "Malaysia", flag: "🇲🇾", nationality: "Malaysian", iso: "MY" },
  { code: "+960", country: "Maldives", flag: "🇲🇻", nationality: "Maldivian", iso: "MV" },
  { code: "+223", country: "Mali", flag: "🇲🇱", nationality: "Malian", iso: "ML" },
  { code: "+356", country: "Malta", flag: "🇲🇹", nationality: "Maltese", iso: "MT" },
  { code: "+692", country: "Marshall Islands", flag: "🇲🇭", nationality: "Marshallese", iso: "MH" },
  { code: "+222", country: "Mauritania", flag: "🇲🇷", nationality: "Mauritanian", iso: "MR" },
  { code: "+230", country: "Mauritius", flag: "🇲🇺", nationality: "Mauritian", iso: "MU" },
  { code: "+52", country: "Mexico", flag: "🇲🇽", nationality: "Mexican", iso: "MX" },
  { code: "+691", country: "Micronesia", flag: "🇫🇲", nationality: "Micronesian", iso: "FM" },
  { code: "+373", country: "Moldova", flag: "🇲🇩", nationality: "Moldovan", iso: "MD" },
  { code: "+377", country: "Monaco", flag: "🇲🇨", nationality: "Monegasque", iso: "MC" },
  { code: "+976", country: "Mongolia", flag: "🇲🇳", nationality: "Mongolian", iso: "MN" },
  { code: "+382", country: "Montenegro", flag: "🇲🇪", nationality: "Montenegrin", iso: "ME" },
  { code: "+212", country: "Morocco", flag: "🇲🇦", nationality: "Moroccan", iso: "MA" },
  { code: "+258", country: "Mozambique", flag: "🇲🇿", nationality: "Mozambican", iso: "MZ" },
  { code: "+95", country: "Myanmar", flag: "🇲🇲", nationality: "Burmese", iso: "MM" },
  { code: "+264", country: "Namibia", flag: "🇳🇦", nationality: "Namibian", iso: "NA" },
  { code: "+674", country: "Nauru", flag: "🇳🇷", nationality: "Nauruan", iso: "NR" },
  { code: "+977", country: "Nepal", flag: "🇳🇵", nationality: "Nepali", iso: "NP" },
  { code: "+31", country: "Netherlands", flag: "🇳🇱", nationality: "Dutch", iso: "NL" },
  { code: "+64", country: "New Zealand", flag: "🇳🇿", nationality: "New Zealander", iso: "NZ" },
  { code: "+505", country: "Nicaragua", flag: "🇳🇮", nationality: "Nicaraguan", iso: "NI" },
  { code: "+227", country: "Niger", flag: "🇳🇪", nationality: "Nigerien", iso: "NE" },
  { code: "+234", country: "Nigeria", flag: "🇳🇬", nationality: "Nigerian", iso: "NG" },
  { code: "+389", country: "North Macedonia", flag: "🇲🇰", nationality: "Macedonian", iso: "MK" },
  { code: "+47", country: "Norway", flag: "🇳🇴", nationality: "Norwegian", iso: "NO" },
  { code: "+968", country: "Oman", flag: "🇴🇲", nationality: "Omani", iso: "OM" },
  { code: "+92", country: "Pakistan", flag: "🇵🇰", nationality: "Pakistani", iso: "PK" },
  { code: "+680", country: "Palau", flag: "🇵🇼", nationality: "Palauan", iso: "PW" },
  { code: "+970", country: "Palestine", flag: "🇵🇸", nationality: "Palestinian", iso: "PS" },
  { code: "+507", country: "Panama", flag: "🇵🇦", nationality: "Panamanian", iso: "PA" },
  { code: "+675", country: "Papua New Guinea", flag: "🇵🇬", nationality: "Papua New Guinean", iso: "PG" },
  { code: "+595", country: "Paraguay", flag: "🇵🇾", nationality: "Paraguayan", iso: "PY" },
  { code: "+51", country: "Peru", flag: "🇵🇪", nationality: "Peruvian", iso: "PE" },
  { code: "+63", country: "Philippines", flag: "🇵🇭", nationality: "Filipino", iso: "PH" },
  { code: "+48", country: "Poland", flag: "🇵🇱", nationality: "Polish", iso: "PL" },
  { code: "+351", country: "Portugal", flag: "🇵🇹", nationality: "Portuguese", iso: "PT" },
  { code: "+974", country: "Qatar", flag: "🇶🇦", nationality: "Qatari", iso: "QA" },
  { code: "+40", country: "Romania", flag: "🇷🇴", nationality: "Romanian", iso: "RO" },
  { code: "+7", country: "Russia", flag: "🇷🇺", nationality: "Russian", iso: "RU" },
  { code: "+250", country: "Rwanda", flag: "🇷🇼", nationality: "Rwandan", iso: "RW" },
  { code: "+1869", country: "Saint Kitts and Nevis", flag: "🇰🇳", nationality: "Kittitian", iso: "KN" },
  { code: "+1758", country: "Saint Lucia", flag: "🇱🇨", nationality: "Saint Lucian", iso: "LC" },
  { code: "+1784", country: "Saint Vincent", flag: "🇻🇨", nationality: "Vincentian", iso: "VC" },
  { code: "+685", country: "Samoa", flag: "🇼🇸", nationality: "Samoan", iso: "WS" },
  { code: "+378", country: "San Marino", flag: "🇸🇲", nationality: "Sammarinese", iso: "SM" },
  { code: "+239", country: "São Tomé and Príncipe", flag: "🇸🇹", nationality: "São Toméan", iso: "ST" },
  { code: "+966", country: "Saudi Arabia", flag: "🇸🇦", nationality: "Saudi Arabian", iso: "SA" },
  { code: "+221", country: "Senegal", flag: "🇸🇳", nationality: "Senegalese", iso: "SN" },
  { code: "+381", country: "Serbia", flag: "🇷🇸", nationality: "Serbian", iso: "RS" },
  { code: "+248", country: "Seychelles", flag: "🇸🇨", nationality: "Seychellois", iso: "SC" },
  { code: "+232", country: "Sierra Leone", flag: "🇸🇱", nationality: "Sierra Leonean", iso: "SL" },
  { code: "+65", country: "Singapore", flag: "🇸🇬", nationality: "Singaporean", iso: "SG" },
  { code: "+421", country: "Slovakia", flag: "🇸🇰", nationality: "Slovak", iso: "SK" },
  { code: "+386", country: "Slovenia", flag: "🇸🇮", nationality: "Slovenian", iso: "SI" },
  { code: "+677", country: "Solomon Islands", flag: "🇸🇧", nationality: "Solomon Islander", iso: "SB" },
  { code: "+252", country: "Somalia", flag: "🇸🇴", nationality: "Somali", iso: "SO" },
  { code: "+27", country: "South Africa", flag: "🇿🇦", nationality: "South African", iso: "ZA" },
  { code: "+211", country: "South Sudan", flag: "🇸🇸", nationality: "South Sudanese", iso: "SS" },
  { code: "+34", country: "Spain", flag: "🇪🇸", nationality: "Spanish", iso: "ES" },
  { code: "+94", country: "Sri Lanka", flag: "🇱🇰", nationality: "Sri Lankan", iso: "LK" },
  { code: "+249", country: "Sudan", flag: "🇸🇩", nationality: "Sudanese", iso: "SD" },
  { code: "+597", country: "Suriname", flag: "🇸🇷", nationality: "Surinamese", iso: "SR" },
  { code: "+46", country: "Sweden", flag: "🇸🇪", nationality: "Swedish", iso: "SE" },
  { code: "+41", country: "Switzerland", flag: "🇨🇭", nationality: "Swiss", iso: "CH" },
  { code: "+963", country: "Syria", flag: "🇸🇾", nationality: "Syrian", iso: "SY" },
  { code: "+886", country: "Taiwan", flag: "🇹🇼", nationality: "Taiwanese", iso: "TW" },
  { code: "+992", country: "Tajikistan", flag: "🇹🇯", nationality: "Tajik", iso: "TJ" },
  { code: "+255", country: "Tanzania", flag: "🇹🇿", nationality: "Tanzanian", iso: "TZ" },
  { code: "+66", country: "Thailand", flag: "🇹🇭", nationality: "Thai", iso: "TH" },
  { code: "+228", country: "Togo", flag: "🇹🇬", nationality: "Togolese", iso: "TG" },
  { code: "+676", country: "Tonga", flag: "🇹🇴", nationality: "Tongan", iso: "TO" },
  { code: "+1868", country: "Trinidad and Tobago", flag: "🇹🇹", nationality: "Trinidadian", iso: "TT" },
  { code: "+216", country: "Tunisia", flag: "🇹🇳", nationality: "Tunisian", iso: "TN" },
  { code: "+90", country: "Turkey", flag: "🇹🇷", nationality: "Turkish", iso: "TR" },
  { code: "+993", country: "Turkmenistan", flag: "🇹🇲", nationality: "Turkmen", iso: "TM" },
  { code: "+688", country: "Tuvalu", flag: "🇹🇻", nationality: "Tuvaluan", iso: "TV" },
  { code: "+256", country: "Uganda", flag: "🇺🇬", nationality: "Ugandan", iso: "UG" },
  { code: "+380", country: "Ukraine", flag: "🇺🇦", nationality: "Ukrainian", iso: "UA" },
  { code: "+971", country: "United Arab Emirates", flag: "🇦🇪", nationality: "Emirati", iso: "AE" },
  { code: "+44", country: "United Kingdom", flag: "🇬🇧", nationality: "British", iso: "GB" },
  { code: "+1", country: "United States", flag: "🇺🇸", nationality: "American", iso: "US" },
  { code: "+598", country: "Uruguay", flag: "🇺🇾", nationality: "Uruguayan", iso: "UY" },
  { code: "+998", country: "Uzbekistan", flag: "🇺🇿", nationality: "Uzbek", iso: "UZ" },
  { code: "+678", country: "Vanuatu", flag: "🇻🇺", nationality: "Ni-Vanuatu", iso: "VU" },
  { code: "+379", country: "Vatican City", flag: "🇻🇦", nationality: "Vatican", iso: "VA" },
  { code: "+58", country: "Venezuela", flag: "🇻🇪", nationality: "Venezuelan", iso: "VE" },
  { code: "+84", country: "Vietnam", flag: "🇻🇳", nationality: "Vietnamese", iso: "VN" },
  { code: "+967", country: "Yemen", flag: "🇾🇪", nationality: "Yemeni", iso: "YE" },
  { code: "+260", country: "Zambia", flag: "🇿🇲", nationality: "Zambian", iso: "ZM" },
  { code: "+263", country: "Zimbabwe", flag: "🇿🇼", nationality: "Zimbabwean", iso: "ZW" },
];

// Get country code from nationality
export const getCountryCodeFromNationality = (nationality: string): string => {
  const country = worldCountries.find(c => c.nationality.toLowerCase() === nationality.toLowerCase());
  return country?.code || "+880"; // Default to Bangladesh if not found
};

// Get country from nationality
export const getCountryFromNationality = (nationality: string): Country | undefined => {
  return worldCountries.find(c => c.nationality.toLowerCase() === nationality.toLowerCase());
};

// Get all nationalities sorted alphabetically (with common ones first)
export const getNationalities = (): string[] => {
  const commonNationalities = ["Bangladeshi", "Indian", "Pakistani", "Saudi Arabian", "Emirati"];
  const allNationalities = worldCountries.map(c => c.nationality);
  
  // Put common nationalities first, then sort the rest alphabetically
  const commonSet = new Set(commonNationalities);
  const otherNationalities = allNationalities.filter(n => !commonSet.has(n)).sort();
  
  return [...commonNationalities, ...otherNationalities];
};
